export const CUISINE_TYPES: readonly string[] = [
  "Deutsch / Regional",
  "Italienisch",
  "Pizza / Pasta",
  "Türkisch / Döner",
  "Griechisch / Mediterran",
  "Arabisch / Libanesisch",
  "Indisch / Pakistanisch",
  "Japanisch / Sushi",
  "Chinesisch",
  "Vietnamesisch",
  "Thailändisch",
  "Koreanisch",
  "Mexikanisch",
  "Amerikanisch / Burger",
  "Street Food / Imbiss",
  "Café / Brunch",
  "Shisha-Bar / Lounge",
  "Vegetarisch / Vegan",
  "Sonstiges",
] as const;
